packages:
  - "apps/*"
  - "packages/*"

# Enable shared dependencies hoisting for better performance
link-workspace-packages: true

# Prevent accidental publishing of private packages
shared-workspace-lockfile: true

# Catalog for managing versions across workspace
catalog:
  # Core dependencies
  typescript: ^5.6.0
  "@types/node": ^22.0.0
  vitest: ^2.0.0
  
  # Backend dependencies
  fastify: ^5.0.0
  "@trpc/server": ^10.45.0
  zod: ^3.23.0
  prisma: ^5.20.0
  "@prisma/client": ^5.20.0
  redis: ^4.7.0
  "@elastic/elasticsearch": ^8.15.0
  
  # Frontend dependencies
  react: ^18.3.0
  "react-dom": ^18.3.0
  "next": ^14.2.0
  "@tanstack/react-query": ^5.52.0
  "@trpc/client": ^10.45.0
  "@trpc/react-query": ^10.45.0
  "tailwindcss": ^3.4.0
  "@headlessui/react": ^2.1.0
  "lucide-react": ^0.441.0
  
  # Testing dependencies
  "@testing-library/react": ^16.0.0
  "@testing-library/jest-dom": ^6.5.0
  "@playwright/test": ^1.47.0
  "happy-dom": ^15.7.0
  
  # Development tools
  "eslint": ^9.0.0
  "prettier": ^3.3.0
  "@typescript-eslint/eslint-plugin": ^8.0.0
  "@typescript-eslint/parser": ^8.0.0 